### PR TITLE
Python3 Development

### PR DESCRIPTION
**Pull request by shinybrar**
First attempt at making the package working in python3, changes include:
  - Added pre-commit file for linting code
  - Translation of python2->python3 for most changes, eg. buffer object look in `mpiutil`
    ```python
    #from
    buf = buffer(obj)
    #to
    buf = memoryview(obj)
    ```
  - Updated setup to meet post PEP517 standards

### CODE REVIEW

**Review by jrs65 — CHANGES_REQUESTED** [review]
Thanks @shinybrar it looks good, but please remove the `.pre-commit-config.yaml` file.

**Comment by jrs65** [comment]
Also, I guess this should depend on `caput` for the `mpiutil` module rather than incorporating an ancient version directly.

**Comment by jrs65** [comment]
@shinybrar should I expect this PR to come back? The changes looked great. I was just looking at adding a quick commit that got rid of the vendored mpiutil.

**Comment by sievers** [comment]
Hey folks - I'm working on finishing of the CUDA version of the circulant inverter.  A couple of quick questions - is the input generally going to be float32?  I imagine the slowest step is going to be the copying to/from the GPU, so if you really only have int8, it'll be quite a bit faster.  Also, is the last channel usually going to be missing?  It's easy to clean that up on the GPU (and in fact free if you're switching from int8 to fp32), but I'd like to get started just with the most common use-case.

Cheers,

Jon
________________________________

**Pull request closed without merging**
